#include "bonusblock.h" // generated by grit from gfx/bonusblock.png

#define BONUS_TILESET 3

Rage::TileSetDefinition bonusDef;
bonusDef.version = 1;
bonusDef.tileSetID = BONUS_TILESET;
bonusDef.image.gfx = bonusblockTiles;
bonusDef.image.gfxLen = bonusblockTilesLen;
bonusDef.image.pal = bonusblockPal;
bonusDef.image.palLen = bonusblockPalLen;
