#!/bin/bash

if [ -z "$1" ]
then
    echo "Usage:"
    echo "$0 RAGE_VERSION"
    echo "Example: $0 0.2.4"
else
    scp files/rage-$1.* files/rage-src-$1.* remar@ftp.scorpionshops.com:~/remar.se/www/andreas/rage/files/.
fi
