#include "metroid.h" // generated by grit from gfx/metroid.png

#define METROID_TILESET 2

Rage::TileSetDefinition metroidDef;
metroidDef.version = 2;
metroidDef.tileSetID = METROID_TILESET;
metroidDef.image.gfx = metroidTiles;
metroidDef.image.gfxLen = metroidTilesLen;
metroidDef.image.pal = metroidPal;
metroidDef.image.palLen = metroidPalLen;
