#include "block.h" // generated by grit from gfx/block.png and gfx/block.grit

#define BLOCK_TILESET 1

Rage::TileSetDefinition blockDef;
blockDef.version = 2;
blockDef.tileSetID = BLOCK_TILESET;
blockDef.image.gfx = blockTiles;
blockDef.image.gfxLen = blockTilesLen;
blockDef.image.pal = blockPal;
blockDef.image.palLen = blockPalLen;

